#!/usr/bin/env python3
"""Compile and deploy the worktree-local Henia/Phora prototype."""

import json
import os
from pathlib import Path
import shutil
import subprocess
import sys
import tempfile
import tomllib

ROOT = Path(__file__).resolve().parents[2]
STATE = ROOT / ".henia"
OWNER = "Generated by prototype/henia/deploy.py from canonical Tropos sources.\n"


def confined(path):
    path = Path(os.path.abspath(path))
    if not path.is_relative_to(ROOT) or path == ROOT:
        raise RuntimeError(f"path escapes prototype: {path}")
    for parent in (path, *path.parents):
        if parent == ROOT:
            break
        if parent.is_symlink():
            raise RuntimeError(f"symlinked prototype path: {parent}")
    return path


def check_tree(path):
    confined(path)
    if path.exists():
        for item in path.rglob("*"):
            if item.is_symlink():
                raise RuntimeError(f"symlinked prototype artifact: {item}")


def run(args, cwd=ROOT, **kwargs):
    print("+", " ".join(map(str, args)), flush=True)
    return subprocess.run(args, cwd=cwd, check=True, **kwargs)


def check_owned(path):
    check_tree(path)
    if path.exists():
        marker = path / "GENERATED.md"
        if not marker.is_file() or marker.read_text() != OWNER:
            raise RuntimeError(f"unowned build output: {path}")


def snapshot(path, previous):
    check_owned(previous)
    if (previous / ".git").is_dir():
        check_tree(previous / ".git")
        shutil.copytree(previous / ".git", path / ".git")
    else:
        run(["git", "init", "-q", "--initial-branch=artifacts", str(path)])
    run(["git", "-C", str(path), "add", "-A"])
    changed = subprocess.run(["git", "-C", str(path), "diff", "--cached", "--quiet"])
    if changed.returncode == 1:
        run(["git", "-C", str(path), "-c", "user.name=Tropos artifact compiler",
             "-c", "user.email=generated@localhost", "commit", "--no-gpg-sign",
             "-qm", "Compile canonical artifacts"])
    elif changed.returncode:
        raise RuntimeError(f"cannot inspect artifact index: {path}")


def publish(output, live):
    check_owned(live)
    if live.exists():
        live.rename(output.with_name(output.name + "-previous"))
    output.rename(live)


def prepare():
    config = tomllib.loads((ROOT / "prototype/henia/stage/phora.toml").read_text())
    output = Path(tempfile.mkdtemp(prefix="input-", dir=STATE))
    (output / "GENERATED.md").write_text(OWNER)
    for pattern in config["sources"]["canonical"]["include"]:
        for item in ROOT.glob(pattern):
            confined(item)
            if item.is_file():
                target = output / item.relative_to(ROOT)
                target.parent.mkdir(parents=True, exist_ok=True)
                shutil.copy2(item, target)
    snapshot(output, STATE / "input")
    publish(output, STATE / "input")


def build():
    source = STATE / "canonical"
    check_tree(source)
    output = Path(tempfile.mkdtemp(prefix="build-", dir=STATE))
    (output / "GENERATED.md").write_text(OWNER)
    run(["henia", "build", str(source), "--config", str(ROOT / "henia.toml"),
         "--output", str(output)])
    for harness in ("claude", "codex"):
        target = output / harness
        for resource in ("agents", "instructions"):
            shutil.copytree(source / resource, target / resource)
        (target / "GENERATED.md").write_text(OWNER)
        check_tree(target)
        result = subprocess.run(
            ["henia", "lint", str(target), "--config", str(ROOT / "henia.toml"),
             "--format", "json"], cwd=ROOT, text=True, capture_output=True)
        (output / f"{harness}-lint.json").write_text(result.stdout)
        (output / f"{harness}-lint.stderr").write_text(result.stderr)
        if result.returncode:
            raise RuntimeError(f"{harness} lint failed; evidence: {output}")
        diagnostics = json.loads(result.stdout)
        print(f"{harness}: {len(diagnostics)} lint diagnostics; {output}")
        snapshot(target, STATE / "build" / harness)
    publish(output, STATE / "build")


def main():
    for name in (".henia", ".claude", ".codex"):
        confined(ROOT / name)
    STATE.mkdir(exist_ok=True)
    if sys.argv[1:] == ["build"]:
        build()
        return
    if sys.argv[1:]:
        raise RuntimeError("usage: python3 prototype/henia/deploy.py [build]")
    for target in (ROOT / ".claude", ROOT / ".codex", STATE / "canonical"):
        check_tree(target)
    prepare()
    for phase in ("stage", "deploy"):
        run(["phora", "update", "--fast-forward"], ROOT / "prototype" / "henia" / phase)
    run(["phora", "verify"], ROOT / "prototype" / "henia" / "deploy")


if __name__ == "__main__":
    try:
        main()
    except (RuntimeError, subprocess.CalledProcessError) as error:
        sys.exit(str(error))
