#!/usr/bin/env python3
"""Native subagent routing: registry defaults, per-tree overrides, and the PreToolUse
rewrite that sends a role to a proxy-served model.

`Task(model=...)` only accepts Anthropic aliases and carries no effort at all, so both can
be named only in an agent definition's frontmatter. `sync` materialises one definition per
(role, proxy peer, declared effort); `hook` swaps `subagent_type` to the matching one.
"""

from __future__ import annotations

import functools
import json
import os
import subprocess
import sys
import urllib.error
import urllib.request
from typing import NamedTuple

FRONTMATTER = "---"
OVERRIDE_NAME = "routing"
MARKER = "generated by `peer route sync`"
ROUTE_USAGE = """usage: peer route <hook|sync|show|check ROLE=PEER...|set ROLE=PEER...|clear> [-C DIR]
  show                 Print resolved role, source, and active/inactive status.
  check ROLE=PEER...   Validate generated definitions immediately before direct dispatch.
  sync                 Regenerate routed definitions from base roles and reviewers.yaml.
  set ROLE=PEER...     Override routes beneath DIR; clear removes that override.
  hook                 Internal PreToolUse rewrite; inactive or stale routes are left native.
"""


class Route(NamedTuple):
    peer_id: str
    source: str


def load_registry(path: str) -> dict:
    out = subprocess.run(
        ["yq", "-o=json", ".", path], capture_output=True, text=True, check=False
    )
    if out.returncode != 0:
        raise SystemExit(f"peer route: cannot read registry at {path}")
    return json.loads(out.stdout or "{}")


def peers_by_key(registry: dict) -> dict[str, dict]:
    index: dict[str, dict] = {}
    for entry in registry.get("reviewers") or []:
        index[entry["id"]] = entry
        if entry.get("alias"):
            index[entry["alias"]] = entry
    return index


def routing_defaults(registry: dict) -> dict[str, str]:
    return dict(registry.get("routing") or {})


def override_path(workdir: str) -> str:
    return os.path.join(workdir, ".peer", OVERRIDE_NAME)


def read_override(workdir: str) -> dict[str, str]:
    try:
        with open(override_path(workdir), encoding="utf-8") as handle:
            lines = handle.read().splitlines()
    except FileNotFoundError:
        return {}
    pairs: dict[str, str] = {}
    for line in lines:
        line = line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        role, _, value = line.partition("=")
        pairs[role.strip()] = value.strip()
    return pairs


def resolve(registry: dict, workdir: str) -> dict[str, Route]:
    index = peers_by_key(registry)
    resolved: dict[str, Route] = {}
    for role, value in routing_defaults(registry).items():
        entry = index.get(value)
        resolved[role] = Route(entry["id"] if entry else value, "registry")
    for role, value in read_override(workdir).items():
        if role not in resolved:
            continue
        entry = index.get(value)
        resolved[role] = Route(entry["id"] if entry else value, "override")
    return resolved


def proxy_peers(registry: dict) -> list[dict]:
    return [e for e in registry.get("reviewers") or [] if e.get("proxy")]


def write_atomically(target: str, text: str) -> None:
    """A generated definition is live the moment it lands, so a partial write is a
    broken agent — and replacing a symlink beats writing through one."""
    staged = f"{target}.staged"
    with open(staged, "w", encoding="utf-8") as handle:
        handle.write(text)
    os.replace(staged, target)


def split_frontmatter(text: str) -> tuple[list[str], str]:
    lines = text.splitlines()
    if not lines or lines[0].strip() != FRONTMATTER:
        raise ValueError("no frontmatter")
    end = next(
        (i for i, line in enumerate(lines[1:], 1) if line.strip() == FRONTMATTER), None
    )
    if end is None:
        raise ValueError("frontmatter is never closed")
    return lines[1:end], "\n".join(lines[end + 1 :])


def effort_levels(registry: dict) -> list[str]:
    return [str(e).strip() for e in registry.get("efforts") or [] if str(e).strip()]


def render(role_text: str, name: str, peer: dict | None, effort: str = "") -> str:
    front, body = split_frontmatter(role_text)
    dropped = ["name:", "color:", "model:"] + (["effort:"] if effort else [])
    kept = [ln for ln in front if not ln.startswith(tuple(dropped))]
    kept.insert(0, f"name: {name}")
    if peer:
        kept.append(f"model: {peer['model']}")
    if effort:
        kept.append(f"effort: {effort}")
    source = ", ".join(
        filter(None, [peer["id"] if peer else "", f"effort {effort}" if effort else ""])
    )
    marker = (
        f"<!-- {MARKER} from reviewers.yaml ({source}); "
        f"edit the role definition, not this file -->"
    )
    return "\n".join([FRONTMATTER, *kept, FRONTMATTER, marker, body]).rstrip() + "\n"


def is_generated(path: str) -> bool:
    try:
        with open(path, encoding="utf-8") as handle:
            return MARKER in handle.read(4096)
    except OSError:
        return False


def cmd_sync(registry: dict, agents_dir: str) -> int:
    """Render everything before writing anything: a half-applied sync leaves live agent
    definitions that no role file explains."""
    agents_dir = agents_dir.split(os.pathsep)[0]
    peers = proxy_peers(registry)
    levels = effort_levels(registry)
    # `<role>-<x>` has to name one thing: an alias that is also a level makes it two.
    clash = {p["alias"] for p in peers} & set(levels)
    if clash:
        sys.stderr.write(
            f"peer route sync: effort {', '.join(sorted(clash))} collides with a peer alias\n"
        )
        return 1
    variants = [(p, "") for p in peers]
    variants += [(p, lvl) for p in peers for lvl in levels]
    variants += [(None, lvl) for lvl in levels]

    planned: dict[str, str] = {}
    for role in routing_defaults(registry):
        source = os.path.join(agents_dir, f"{role}.md")
        try:
            with open(source, encoding="utf-8") as handle:
                role_text = handle.read()
        except OSError as err:
            sys.stderr.write(f"peer route sync: cannot read {source}: {err.strerror}\n")
            return 1
        for peer, effort in variants:
            name = "-".join(filter(None, [role, peer["alias"] if peer else "", effort]))
            try:
                planned[f"{name}.md"] = render(role_text, name, peer, effort)
            except ValueError as err:
                sys.stderr.write(f"peer route sync: {source}: {err}\n")
                return 1

    for filename, text in sorted(planned.items()):
        target = os.path.join(agents_dir, filename)
        write_atomically(target, text)
        print(target)

    for entry in sorted(os.listdir(agents_dir)):
        if not entry.endswith(".md") or entry in planned:
            continue
        stale = os.path.join(agents_dir, entry)
        if is_generated(stale):
            os.remove(stale)
            print(f"removed {stale}")
    return 0 if planned else 1


def definition_path(agents_dir: str, name: str) -> str | None:
    for root in agents_dir.split(os.pathsep):
        candidate = os.path.join(root, f"{name}.md")
        if os.path.isfile(candidate):
            return candidate
    return None


def definition_status(
    agents_dir: str, role: str, peer: dict | None, effort: str = ""
) -> str:
    name = "-".join(filter(None, [role, peer["alias"] if peer else "", effort]))
    target = definition_path(agents_dir, name)
    if not target:
        return "inactive: no definition — run `peer route sync`"
    source = definition_path(agents_dir, role)
    if not source:
        return "inactive: no base role — run `mise run install-peer`"
    try:
        with open(source, encoding="utf-8") as handle:
            expected = render(handle.read(), name, peer, effort)
        with open(target, encoding="utf-8") as handle:
            actual = handle.read()
    except (OSError, ValueError):
        return "inactive: unreadable definition — run `peer route sync`"
    if actual != expected:
        return "inactive: stale definition — run `peer route sync`"
    return "active"


def route_status(
    registry: dict, route: Route, role: str, agents_dir: str, effort: str = ""
) -> str:
    """What `hook` would do with this route — `/implement` reads this to learn what runs."""
    if route.peer_id == "inherit":
        return "-"
    peer = peers_by_key(registry).get(route.peer_id)
    if not peer:
        return "inactive: unknown peer"
    if peer.get("native"):
        if peer.get("harness") != "claude":
            return "inactive: native to another host"
        return definition_status(agents_dir, role, None, effort) if effort else "active"
    if not peer.get("proxy"):
        return "inactive: not proxy-served"
    base_url = os.environ.get("ANTHROPIC_BASE_URL")
    if not base_url:
        return "inactive: no proxy configured"
    if not proxy_is_up(base_url):
        return "inactive: proxy unreachable"
    return definition_status(agents_dir, role, peer, effort)


def cmd_show(registry: dict, workdir: str, agents_dir: str) -> int:
    for role, route in sorted(resolve(registry, workdir).items()):
        status = route_status(registry, route, role, agents_dir)
        print(f"{role:<14} {route.peer_id:<20} {route.source:<10} {status}")
    return 0


def cmd_check(registry: dict, agents_dir: str, assignments: list[str]) -> int:
    """Naming a generated definition on a Task bypasses the hook, and with it every
    precondition the hook checks. This is that check, asked ahead of the dispatch."""
    roles = routing_defaults(registry)
    index = peers_by_key(registry)
    if not assignments:
        sys.stderr.write("usage: peer route check ROLE=PEER...\n")
        return 2
    levels = effort_levels(registry)
    failed = False
    for assignment in assignments:
        role, _, value = assignment.partition("=")
        role, value = role.strip(), value.strip()
        value, _, effort = value.partition("@")
        if role not in roles:
            sys.stderr.write(
                f"peer route check: unknown role '{role}' (have: {', '.join(sorted(roles))})\n"
            )
            return 2
        if effort and effort not in levels:
            sys.stderr.write(
                f"peer route check: '{effort}' is not a declared effort variant "
                f"(have: {', '.join(levels) or 'none'})\n"
            )
            return 2
        peer = index.get(value)
        status = route_status(
            registry,
            Route(peer["id"] if peer else value, "check"),
            role,
            agents_dir,
            effort,
        )
        label = f"{value}@{effort}" if effort else value
        print(f"{role:<14} {label:<20} {status}")
        failed |= status != "active"
    return 1 if failed else 0


def cmd_set(registry: dict, workdir: str, assignments: list[str]) -> int:
    roles = routing_defaults(registry)
    index = peers_by_key(registry)
    pending = read_override(workdir)
    for assignment in assignments:
        role, _, value = assignment.partition("=")
        role, value = role.strip(), value.strip()
        if role not in roles:
            sys.stderr.write(
                f"peer route set: unknown role '{role}' (have: {', '.join(sorted(roles))})\n"
            )
            return 2
        if value != "inherit" and value not in index:
            sys.stderr.write(
                f"peer route set: unknown peer '{value}' (see: peer list)\n"
            )
            return 2
        if value != "inherit":
            entry = index[value]
            if not entry.get("proxy") and not (
                entry.get("native") and entry.get("harness") == "claude"
            ):
                sys.stderr.write(
                    f"peer route set: '{value}' is not a Claude Code route\n"
                )
                return 2
        pending[role] = index[value]["id"] if value in index else value
    os.makedirs(os.path.dirname(override_path(workdir)), exist_ok=True)
    body = "".join(f"{role}={value}\n" for role, value in sorted(pending.items()))
    try:
        write_atomically(override_path(workdir), body)
    except OSError as err:
        sys.stderr.write(f"peer route set: cannot write the override: {err.strerror}\n")
        return 2
    return 0


def cmd_clear(workdir: str) -> int:
    try:
        os.remove(override_path(workdir))
    except FileNotFoundError:
        pass
    except OSError as err:
        sys.stderr.write(
            f"peer route clear: cannot remove {override_path(workdir)}: {err.strerror}\n"
        )
        return 2
    return 0


@functools.cache
def proxy_is_up(base_url: str) -> bool:
    try:
        with urllib.request.urlopen(
            f"{base_url.rstrip('/')}/healthz", timeout=1
        ) as res:
            return res.status == 200
    except (OSError, urllib.error.URLError, ValueError):
        return False


def cmd_hook(registry: dict, workdir: str, agents_dir: str) -> int:
    """Silent no-op is the safe outcome: a declined rewrite lands on the Claude agent,
    a wrong one lands on a model the session cannot reach."""
    try:
        payload = json.load(sys.stdin)
    except (json.JSONDecodeError, UnicodeDecodeError):
        return 0
    if not isinstance(payload, dict):
        return 0
    if payload.get("tool_name") not in ("Task", "Agent"):
        return 0
    tool_input = payload.get("tool_input")
    if not isinstance(tool_input, dict):
        return 0
    role = tool_input.get("subagent_type")
    if not isinstance(role, str):
        return 0
    if isinstance(tool_input.get("model"), str) and tool_input["model"]:
        return 0

    routed = resolve(registry, workdir).get(role)
    if not routed or routed.peer_id == "inherit":
        return 0
    status = route_status(registry, routed, role, agents_dir)
    if status != "active":
        if "definition" in status or "base role" in status:
            sys.stderr.write(f"peer route: {role}: {status}\n")
        return 0

    peer = peers_by_key(registry)[routed.peer_id]
    if peer.get("native"):
        target = role
        updated = {**tool_input, "model": peer["alias"]}
    else:
        target = f"{role}-{peer['alias']}"
        updated = {**tool_input, "subagent_type": target}

    sys.stderr.write(
        f"peer route: {role} -> {target} ({peer['model']}, {routed.source})\n"
    )
    json.dump(
        {
            "hookSpecificOutput": {
                "hookEventName": "PreToolUse",
                "updatedInput": updated,
            }
        },
        sys.stdout,
    )
    print()
    return 0


def main(argv: list[str]) -> int:
    options = {"--registry": "", "--agents-dir": "", "--workdir": os.getcwd()}
    rest: list[str] = []
    index = 0
    while index < len(argv):
        if argv[index] in options:
            options[argv[index]] = argv[index + 1]
            index += 2
            continue
        rest.append(argv[index])
        index += 1

    if not rest:
        sys.stderr.write(ROUTE_USAGE)
        return 2
    action, args = rest[0], rest[1:]

    if action in ("--help", "-h", "help"):
        sys.stdout.write(ROUTE_USAGE)
        return 0
    if action == "clear":
        return cmd_clear(options["--workdir"])

    registry = load_registry(options["--registry"])
    if action == "hook":
        return cmd_hook(registry, options["--workdir"], options["--agents-dir"])
    if action == "sync":
        return cmd_sync(registry, options["--agents-dir"])
    if action == "show":
        return cmd_show(registry, options["--workdir"], options["--agents-dir"])
    if action == "check":
        return cmd_check(registry, options["--agents-dir"], args)
    if action == "set":
        return cmd_set(registry, options["--workdir"], args)
    sys.stderr.write(f"peer route: unknown action '{action}'\n")
    return 2


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
